# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application_info.proto
# Protobuf Python Version: 4.25.7
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pplication_info.proto\"\xd9\x01\n\x0e\x41ppGetResponse\x12\x15\n\rclientVersion\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61taVersion\x18\x02 \x01(\t\x12\x11\n\tappStatus\x18\x03 \x01(\t\x12\x14\n\x0c\x63lientStatus\x18\x04 \x01(\t\x12\x0e\n\x06schema\x18\x05 \x01(\t\x12\r\n\x05gacha\x18\x07 \x01(\t\x12\x11\n\tmultiLive\x18\x08 \x01(\t\x12\x10\n\x08starShop\x18\t \x01(\t\x12\x19\n\x11masterDataVersion\x18\n \x01(\t\x12\x13\n\x0bphotonAppId\x18\x0b \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'application_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_APPGETRESPONSE']._serialized_start=27
  _globals['_APPGETRESPONSE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
