# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: assetbundle_info.proto
# Protobuf Python Version: 4.25.7
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61ssetbundle_info.proto\x12\x10\x61ssetbundle_info\"\x8e\x01\n\x12\x41ssetBundleElement\x12\x12\n\nBundleName\x18\x01 \x01(\t\x12\x0c\n\x04Hash\x18\x02 \x01(\t\x12\x0f\n\x07Version\x18\x03 \x01(\t\x12\x10\n\x08\x43\x61tegory\x18\x04 \x01(\t\x12\x0b\n\x03\x43rc\x18\x05 \x01(\r\x12\x14\n\x0c\x44\x65pendencies\x18\x06 \x03(\t\x12\x10\n\x08\x46ileSize\x18\x07 \x01(\x03\"\xb9\x01\n\x0f\x41ssetBundleInfo\x12\x0f\n\x07Version\x18\x01 \x01(\t\x12?\n\x07\x42undles\x18\x02 \x03(\x0b\x32..assetbundle_info.AssetBundleInfo.BundlesEntry\x1aT\n\x0c\x42undlesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.assetbundle_info.AssetBundleElement:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assetbundle_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ASSETBUNDLEINFO_BUNDLESENTRY']._options = None
  _globals['_ASSETBUNDLEINFO_BUNDLESENTRY']._serialized_options = b'8\001'
  _globals['_ASSETBUNDLEELEMENT']._serialized_start=45
  _globals['_ASSETBUNDLEELEMENT']._serialized_end=187
  _globals['_ASSETBUNDLEINFO']._serialized_start=190
  _globals['_ASSETBUNDLEINFO']._serialized_end=375
  _globals['_ASSETBUNDLEINFO_BUNDLESENTRY']._serialized_start=291
  _globals['_ASSETBUNDLEINFO_BUNDLESENTRY']._serialized_end=375
# @@protoc_insertion_point(module_scope)
